text = %q[ID [nvarchar](max) NOT NULL,
	TYPE_FK [nvarchar](max) NULL,
	ORGANIZATION_FULLNAME [nvarchar](max) NULL,
	ORGANIZATION_SHORTNAME [nvarchar](max) NULL,
	LASTNAME [nvarchar](255) NULL,
	FIRSTNAME [nvarchar](255) NULL,
	PATRONYMIC [nvarchar](255) NULL,
	PHONES [nvarchar](255) NULL,
	FAXES [nvarchar](255) NULL,
	EMAILS [nvarchar](255) NULL,
	OGRN [nvarchar](50) NULL,
	INN [nvarchar](50) NULL,
	KPP [nvarchar](50) NULL,
	L_ADDRESS [nvarchar](max) NULL,
	L_ADDRESS_COUNTRY_FK [nvarchar](max) NULL,
	L_ADDRESS_REGION_FK [nvarchar](max) NULL,
	L_ADDRESS_DISTRICT [nvarchar](255) NULL,
	L_ADDRESS_TOWN [nvarchar](255) NULL,
	L_ADDRESS_STREET [nvarchar](255) NULL,
	L_ADDRESS_HOUSE_NUMBER [nvarchar](255) NULL,
	L_ADDRESS_POSTAL_CODE [nvarchar](50) NULL,
	P_ADDRESS [nvarchar](max) NULL,
	P_ADDRESS_COUNTRY_FK [nvarchar](max) NULL,
	P_ADDRESS_REGION_FK [nvarchar](max) NULL,
	P_ADDRESS_DISTRICT [nvarchar](255) NULL,
	P_ADDRESS_TOWN [nvarchar](255) NULL,
	P_ADDRESS_STREET [nvarchar](255) NULL,
	P_ADDRESS_HOUSE_NUMBER [nvarchar](255) NULL,
	P_ADDRESS_POSTAL_CODE [nvarchar](50) NULL,
]

result = []
text.split(",\n\t").map {|x| result << x.split[0].intern }
pp result